apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: my-app
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 381492217945.dkr.ecr.us-east-1.amazonaws.com/frontend-test:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 3000
          env:
          - name: backendUrl
            value: "http://backend.my-app:5000"

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: my-app
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: frontend
